In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.linear_model import RidgeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import cross_validation, metrics

C:\Users\mypc\Anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
data = pd.read_csv("train_data.txt")
labels = pd.read_csv("train_labels.txt")

In [5]:
data["labels"] = labels
data

Var1  Var2  Var3  Var4  Var5    Var6  Var7  Var8  Var9  Var10   ...    \
0       NaN   NaN   NaN   NaN   NaN   441.0   0.0   NaN   NaN    NaN   ...     
1       NaN   NaN   NaN   NaN   NaN  1141.0   0.0   NaN   NaN    NaN   ...     
2       NaN   NaN   NaN   NaN   NaN  1764.0   7.0   NaN   NaN    NaN   ...     
3       NaN   NaN   NaN   NaN   NaN  1001.0   7.0   NaN   NaN    NaN   ...     
4       NaN   NaN   NaN   NaN   NaN   721.0  14.0   NaN   NaN    NaN   ...     
5       NaN   NaN   NaN   NaN   NaN   791.0   7.0   NaN   NaN    NaN   ...     
6       NaN   NaN   NaN   0.0   NaN     NaN   NaN   NaN   NaN    NaN   ...     
7       NaN   NaN   NaN   NaN   NaN  1092.0   7.0   NaN   NaN    NaN   ...     
8       NaN   NaN   NaN   NaN   NaN   700.0   7.0   NaN   NaN    NaN   ...     
9       NaN   NaN   NaN   NaN   NaN   735.0   7.0   NaN   NaN    NaN   ...     
10      NaN   NaN   NaN   NaN   NaN   392.0   7.0   NaN   NaN    NaN   ...     
11      NaN   NaN   NaN   NaN   NaN   623.0   7.0   NaN   NaN    NaN   ...     
12      NaN   NaN   NaN   NaN   NaN   714.0   7.0   NaN   NaN    NaN   ...     
13      NaN   NaN   NaN   NaN   NaN  1883.0  14.0   NaN   NaN    NaN   ...     
14      NaN   NaN   NaN   NaN   NaN   651.0   7.0   NaN   NaN    NaN   ...     
15      NaN   NaN   NaN   NaN   NaN  1169.0  14.0   NaN   NaN    NaN   ...     
16      NaN   NaN   NaN   NaN   0.0     NaN   NaN   NaN   NaN    0.0   ...     
17      NaN   NaN   NaN   NaN   NaN    56.0   0.0   NaN   NaN    NaN   ...     
18      NaN   NaN   NaN   NaN   NaN  2079.0   7.0   NaN   NaN    NaN   ...     
19      NaN   NaN   NaN   NaN   NaN   868.0   7.0   NaN   NaN    NaN   ...     
20      NaN   NaN   NaN   NaN   NaN   182.0   0.0   NaN   NaN    NaN   ...     
21      NaN   NaN   NaN   NaN   NaN   399.0   0.0   NaN   NaN    NaN   ...     
22      NaN   NaN   NaN   NaN   NaN   798.0  14.0   NaN   NaN    NaN   ...     
23      NaN   NaN   NaN   NaN   NaN   700.0  14.0   NaN   NaN    NaN   ...     
24      NaN   NaN   NaN   NaN   NaN  1372.0   0.0   NaN   NaN    NaN   ...     
25      NaN   NaN   NaN   NaN   NaN   980.0   7.0   NaN   NaN    NaN   ...     
26      NaN   NaN   NaN   NaN   NaN  1099.0   7.0   NaN   NaN    NaN   ...     
27      NaN   NaN   NaN   NaN   0.0     NaN   NaN   NaN   NaN    0.0   ...     
28      NaN   NaN   NaN   NaN   NaN   154.0   0.0   NaN   NaN    NaN   ...     
29      NaN   NaN   NaN   NaN   NaN  1064.0   7.0   NaN   NaN    NaN   ...     
...     ...   ...   ...   ...   ...     ...   ...   ...   ...    ...   ...     
27970   NaN   NaN   NaN   NaN   NaN   700.0   7.0   NaN   NaN    NaN   ...     
27971   NaN   NaN   NaN   NaN   NaN  1204.0   7.0   NaN   NaN    NaN   ...     
27972   NaN   NaN   NaN   NaN   NaN   819.0   7.0   NaN   NaN    NaN   ...     
27973   NaN   NaN   NaN   NaN   NaN     0.0   7.0   NaN   NaN    NaN   ...     
27974   NaN   0.0   0.0   NaN   NaN     NaN   NaN   NaN   NaN    NaN   ...     
27975   NaN   NaN   NaN   NaN   0.0     NaN   NaN   NaN   NaN    0.0   ...     
27976   NaN   NaN   NaN   NaN   NaN   742.0   7.0   NaN   NaN    NaN   ...     
27977   NaN   NaN   NaN   NaN   0.0     NaN   NaN   NaN   NaN    0.0   ...     
27978   NaN   NaN   NaN   NaN   NaN  3577.0   7.0   NaN   NaN    NaN   ...     
27979   NaN   NaN   NaN   NaN   NaN    14.0   0.0   NaN   NaN    NaN   ...     
27980   NaN   NaN   NaN   NaN   NaN  1435.0   7.0   NaN   NaN    NaN   ...     
27981   NaN   NaN   NaN   NaN   NaN  3066.0  14.0   NaN   NaN    NaN   ...     
27982   NaN   NaN   NaN   NaN   NaN   350.0   0.0   NaN   NaN    NaN   ...     
27983   NaN   NaN   NaN   NaN   NaN   777.0   7.0   NaN   NaN    NaN   ...     
27984   NaN   NaN   NaN   NaN   NaN  1407.0   7.0   NaN   NaN    NaN   ...     
27985   NaN   NaN   NaN   NaN   NaN     7.0   0.0   NaN   NaN    NaN   ...     
27986   NaN   NaN   NaN   NaN   NaN     0.0   0.0   NaN   NaN    NaN   ...     
27987   NaN   NaN   NaN   NaN   NaN  2464.0   7.0   NaN   NaN    NaN   ...     
27988  

In [6]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [7]:
label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder(sparse=False)
for i in range(40):
    integer_encoded = label_encoder.fit_transform(data[data.columns[190 + i]].fillna(0).values)
    #integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    #onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    for j in range(len(data)):
        if type(data[data.columns[190 + i]].values[j]) == str:
            data[data.columns[190 + i]].values[j] = integer_encoded[j]
    print integer_encoded


[0 0 0 ... 0 0 0]
[112 110 326 ...  29 126  17]
[24 24 24 ... 24 24 24]
[0 0 0 ... 2 0 0]
[20 20 20 ... 20 20 20]
[0 0 0 ... 0 0 0]
[123 161  53 ... 168 167  26]
[ 704 3008 2197 ... 1182  466 2013]
[ 982 2851 1171 ... 2733 1717 2050]
[   0    0    0 ... 6423    0    0]
[0 0 0 ... 2 0 0]
[4355 1655 1929 ... 4238 4495  823]
[1 1 1 ... 1 1 1]
[57 40 47 ... 46 10 45]
[1 2 3 ... 1 2 2]
[21  2  7 ...  7  2  7]
[10 10 10 ... 10 10 10]
[1 1 1 ... 1 1 1]
[0 0 0 ... 0 0 0]
[5 5 5 ... 5 5 5]
[0 0 0 ... 0 0 0]
[31 31 31 ... 31 31 31]
[0 0 0 ... 0 0 0]
[   0    0    0 ... 7977    0    0]
[0 0 0 ... 0 0 0]
[1203 1203 1210 ... 1207 1207 1203]
[1492 3170 6011 ... 5552 7685 8098]
[1 1 2 ... 2 2 2]
[11 11 11 ... 11 11 11]
[ 502  152  506 ... 1652  910  906]
[4 4 4 ... 4 4 4]
[2821 1908 2499 ... 2683 2307 2599]
[1 1 1 ... 1 1 4]
[0 0 0 ... 0 0 0]
[0 0 0 ... 2 0 0]
[ 7  8 13 ...  6 19  1]
[2 2 2 ... 2 2 2]
[8 8 8 ... 8 8 8]
[0 0 0 ... 1 0 0]
[0 0 0 ... 0 0 0]


In [8]:
data = data.fillna(0.0)
data.head()

Var1  Var2  Var3  Var4  Var5    Var6  Var7  Var8  Var9  Var10   ...    \
0   0.0   0.0   0.0   0.0   0.0   441.0   0.0   0.0   0.0    0.0   ...     
1   0.0   0.0   0.0   0.0   0.0  1141.0   0.0   0.0   0.0    0.0   ...     
2   0.0   0.0   0.0   0.0   0.0  1764.0   7.0   0.0   0.0    0.0   ...     
3   0.0   0.0   0.0   0.0   0.0  1001.0   7.0   0.0   0.0    0.0   ...     
4   0.0   0.0   0.0   0.0   0.0   721.0  14.0   0.0   0.0    0.0   ...     

   Var222  Var223  Var224  Var225  Var226  Var227  Var228  Var229  Var230  \
0    2821     1.0     0.0     0.0       7       2       8     0.0     0.0   
1    1908     1.0     0.0     0.0       8       2       8     0.0     0.0   
2    2499     1.0     0.0     0.0      13       2       8     0.0     0.0   
3    2739     1.0     0.0     1.0      18       2       2     2.0     0.0   
4      20     1.0     0.0     0.0       2       2       8     0.0     0.0   

   labels  
0      -1  
1      -1  
2      -1  
3      -1  
4      -1  

[5 rows x 231 columns]

In [9]:
data.to_csv("encoded_train_data.txt", index = False)

In [28]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(data[data.columns[:230]], data[data.columns[230]], 
                                                                                    test_size = 0.3,
                                                                                    random_state = 1)

## Ridge

In [30]:
ridge_classifier = RidgeClassifier(random_state = 1)
ridge_classifier.fit(train_data, train_labels)
ridge_predictions = ridge_classifier.predict(test_data)

In [31]:
print test_labels.values

[ 1 -1 -1 ... -1  1 -1]


In [32]:
print ridge_predictions

[-1 -1 -1 ... -1 -1 -1]


In [49]:
ridge_classifier.coef_

array([[ 4.80859718e-03, -5.54870482e-02,  9.35876431e-06,
        -6.58802081e-03, -3.15002339e-08, -1.63333658e-06,
        -2.48968138e-03,  0.00000000e+00,  1.39823166e-02,
        -3.88568775e-09, -1.30211189e-02, -1.50320998e-03,
        -1.00766879e-06,  7.88210909e-04,  0.00000000e+00,
         2.27135753e-04, -1.84122591e-03, -6.25420379e-04,
         2.05379532e-02,  0.00000000e+00,  1.12816086e-04,
        -1.53939229e-04, -1.22271580e-03, -1.86984194e-04,
         8.53742644e-05,  4.99846926e-02, -1.64704401e-02,
         7.22662307e-06, -3.72835483e-02, -2.62908122e-02,
         0.00000000e+00,  0.00000000e+00, -8.65600990e-08,
         1.13337353e-02,  9.94703328e-03,  2.72450115e-08,
        -1.68880652e-08, -1.74706631e-10,  0.00000000e+00,
        -4.86287116e-04, -1.77296064e-03,  0.00000000e+00,
        -5.44704659e-03,  8.41439401e-04,  8.79548270e-07,
         1.89506078e-03, -9.96002311e-04,  0.00000000e+00,
         9.87653926e-04,  1.62338634e-04, -2.11444025e-0

In [50]:
ridge_classifier.intercept_ 

array([-0.64844601])

#### ROC AUC

In [48]:
metrics.roc_auc_score(test_labels, ridge_predictions)

0.4998073465193938

#### precision 

In [46]:
metrics.precision_score(test_labels, ridge_predictions, pos_label = -1)

0.9268786471358819

In [42]:
metrics.precision_score(test_labels, ridge_predictions)

0.0

#### recall

In [43]:
metrics.recall_score(test_labels, ridge_predictions, pos_label = -1)

0.9996146930387876

In [44]:
metrics.recall_score(test_labels, ridge_predictions)

0.0

In [6]:
type(data[data.columns[230]])

pandas.core.series.Series

#### cross_validation

In [54]:
scorer = metrics.make_scorer(metrics.roc_auc_score)
cv_strategy = cross_validation.StratifiedKFold(data[data.columns[230]], n_folds= 4)

In [55]:
ridge_scoring = cross_validation.cross_val_score(ridge_classifier, data[data.columns[:230]], data[data.columns[230]], scoring = scorer, cv = cv_strategy)

In [56]:
print 'Ridge mean:{}, max:{}, min:{}, std:{}'.format(ridge_scoring.mean(), ridge_scoring.max(), 
                                                     ridge_scoring.min(), ridge_scoring.std())

Ridge mean:0.499922904941, max:0.5, min:0.49984582177, std:5.45102363082e-05


## Random forest

In [60]:
rf_classifier = RandomForestClassifier(n_estimators = 50, max_depth = 10, random_state = 1)
rf_classifier.fit(train_data, train_labels)
rf_predictions = rf_classifier.predict(test_data)

#### ROC AUC

In [61]:
metrics.roc_auc_score(test_labels, rf_predictions)

0.5

#### precision 

In [62]:
metrics.precision_score(test_labels, rf_predictions, pos_label = -1)

0.9269047619047619

In [63]:
metrics.precision_score(test_labels, rf_predictions)

C:\Users\mypc\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


0.0

#### recall

In [64]:
metrics.recall_score(test_labels, rf_predictions, pos_label = -1)

1.0

In [65]:
metrics.recall_score(test_labels, rf_predictions)

0.0

#### cross_validation

In [66]:
scorer = metrics.make_scorer(metrics.roc_auc_score)
cv_strategy = cross_validation.StratifiedKFold(data[data.columns[230]], n_folds= 4)

In [67]:
rf_scoring = cross_validation.cross_val_score(rf_classifier, data[data.columns[:230]], data[data.columns[230]], scoring = scorer, cv = cv_strategy)

In [68]:
print 'Random forest mean:{}, max:{}, min:{}, std:{}'.format(rf_scoring.mean(), rf_scoring.max(), 
                                                     rf_scoring.min(), rf_scoring.std())

Random forest mean:0.5, max:0.5, min:0.5, std:0.0


## Gradient boosting

In [70]:
gb_classifier = GradientBoostingClassifier(n_estimators = 50, random_state = 1)
gb_classifier.fit(train_data, train_labels)
gb_predictions = gb_classifier.predict(test_data)

#### ROC AUC

In [71]:
metrics.roc_auc_score(test_labels, gb_predictions)

0.5053792365985553

#### precision 

In [72]:
metrics.precision_score(test_labels, gb_predictions, pos_label = -1)

0.9276347162613257

In [73]:
metrics.precision_score(test_labels, gb_predictions)

0.5833333333333334

#### recall

In [74]:
metrics.recall_score(test_labels, gb_predictions, pos_label = -1)

0.9993578217313126

In [75]:
metrics.recall_score(test_labels, gb_predictions)

0.011400651465798045

#### cross_validation

In [76]:
scorer = metrics.make_scorer(metrics.roc_auc_score)
cv_strategy = cross_validation.StratifiedKFold(data[data.columns[230]], n_folds= 4)

In [78]:
gb_scoring = cross_validation.cross_val_score(gb_classifier, data[data.columns[:230]], data[data.columns[230]], scoring = scorer, cv = cv_strategy)

In [79]:
print 'Gradient boosting mean:{}, max:{}, min:{}, std:{}'.format(gb_scoring.mean(), gb_scoring.max(), 
                                                     gb_scoring.min(), gb_scoring.std())

Gradient boosting mean:0.502228000681, max:0.502835520357, min:0.501633391113, std:0.000503884739997
